//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rebel", Namespace="http://schemas.datacontract.org/2004/07/WCFContracts")]
    public partial class Rebel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFContracts.GeoLocation GeoLocationField;
        
        private System.DateTime JoinningDateField;
        
        private string RebelNameField;
        
        private WCFContracts.Squad SquadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFContracts.GeoLocation GeoLocation
        {
            get
            {
                return this.GeoLocationField;
            }
            set
            {
                this.GeoLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime JoinningDate
        {
            get
            {
                return this.JoinningDateField;
            }
            set
            {
                this.JoinningDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RebelName
        {
            get
            {
                return this.RebelNameField;
            }
            set
            {
                this.RebelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFContracts.Squad Squad
        {
            get
            {
                return this.SquadField;
            }
            set
            {
                this.SquadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoLocation", Namespace="http://schemas.datacontract.org/2004/07/WCFContracts")]
    public partial class GeoLocation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CoordXField;
        
        private int CoordYField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoordX
        {
            get
            {
                return this.CoordXField;
            }
            set
            {
                this.CoordXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoordY
        {
            get
            {
                return this.CoordYField;
            }
            set
            {
                this.CoordYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Squad", Namespace="http://schemas.datacontract.org/2004/07/WCFContracts")]
    public partial class Squad : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string GalacticAreaField;
        
        private string LocationField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalacticArea
        {
            get
            {
                return this.GalacticAreaField;
            }
            set
            {
                this.GalacticAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/WCFContracts")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRebelService")]
public interface IRebelService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRebelService/AddRebel", ReplyAction="http://tempuri.org/IRebelService/AddRebelResponse")]
    string AddRebel(WCFContracts.Rebel rebel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRebelService/AddRebel", ReplyAction="http://tempuri.org/IRebelService/AddRebelResponse")]
    System.Threading.Tasks.Task<string> AddRebelAsync(WCFContracts.Rebel rebel);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRebelService/SendNotification")]
    void SendNotification(WCFContracts.Message message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRebelService/SendNotification")]
    System.Threading.Tasks.Task SendNotificationAsync(WCFContracts.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRebelServiceChannel : IRebelService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RebelServiceClient : System.ServiceModel.ClientBase<IRebelService>, IRebelService
{
    
    public RebelServiceClient()
    {
    }
    
    public RebelServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RebelServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RebelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RebelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string AddRebel(WCFContracts.Rebel rebel)
    {
        return base.Channel.AddRebel(rebel);
    }
    
    public System.Threading.Tasks.Task<string> AddRebelAsync(WCFContracts.Rebel rebel)
    {
        return base.Channel.AddRebelAsync(rebel);
    }
    
    public void SendNotification(WCFContracts.Message message)
    {
        base.Channel.SendNotification(message);
    }
    
    public System.Threading.Tasks.Task SendNotificationAsync(WCFContracts.Message message)
    {
        return base.Channel.SendNotificationAsync(message);
    }
}
